[project]
name = "mdtools"
version = "0.1.0"
license.text = "MIT"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "click>=8.1.8",
    "pyyaml>=6.0.2",
    "sh>=2.2.1",
]

[project.scripts]
mdtools = 'mdtools.cli:main'

[tool.uv]
package = true
